; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=gfx906 < %s | FileCheck --check-prefixes=GFX9-DL %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1011 < %s | FileCheck --check-prefixes=GFX10-DL %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx950 < %s | FileCheck --check-prefixes=GFX950 %s

; Test dot2 patterns with saturating add (clamp)

; Unsigned dot2 with saturation: uaddsat(a[0]*b[0] + a[1]*b[1], c)
define i32 @udot2_sat(<2 x i16> %a, <2 x i16> %b, i32 %c) {
; GFX9-DL-LABEL: udot2_sat:
; GFX9-DL:       ; %bb.0: ; %entry
; GFX9-DL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-DL-NEXT:    v_dot2_u32_u16 v0, v1, v0, v2 clamp
; GFX9-DL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX10-DL-LABEL: udot2_sat:
; GFX10-DL:       ; %bb.0: ; %entry
; GFX10-DL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-DL-NEXT:    v_dot2_u32_u16 v0, v1, v0, v2 clamp
; GFX10-DL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX950-LABEL: udot2_sat:
; GFX950:       ; %bb.0: ; %entry
; GFX950-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX950-NEXT:    v_dot2_u32_u16 v0, v1, v0, v2 clamp
; GFX950-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv.i = zext <2 x i16> %a to <2 x i32>
  %conv6.i = zext <2 x i16> %b to <2 x i32>
  %mul.i = mul nuw <2 x i32> %conv6.i, %conv.i
  %0 = extractelement <2 x i32> %mul.i, i64 0
  %1 = extractelement <2 x i32> %mul.i, i64 1
  %add.i = add i32 %0, %1
  %cond.i.i = tail call i32 @llvm.uadd.sat.i32(i32 %add.i, i32 %c)
  ret i32 %cond.i.i
}

; Signed dot2 with saturation: saddsat(a[0]*b[0] + a[1]*b[1], c)
define i32 @sdot2_sat(<2 x i16> %a, <2 x i16> %b, i32 %c) {
; GFX9-DL-LABEL: sdot2_sat:
; GFX9-DL:       ; %bb.0: ; %entry
; GFX9-DL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-DL-NEXT:    v_dot2_i32_i16 v0, v1, v0, v2 clamp
; GFX9-DL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX10-DL-LABEL: sdot2_sat:
; GFX10-DL:       ; %bb.0: ; %entry
; GFX10-DL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-DL-NEXT:    v_dot2_i32_i16 v0, v1, v0, v2 clamp
; GFX10-DL-NEXT:    s_setpc_b64 s[30:31]
;
; GFX950-LABEL: sdot2_sat:
; GFX950:       ; %bb.0: ; %entry
; GFX950-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX950-NEXT:    v_dot2_i32_i16 v0, v1, v0, v2 clamp
; GFX950-NEXT:    s_setpc_b64 s[30:31]
entry:
  %conv.i = sext <2 x i16> %a to <2 x i32>
  %conv6.i = sext <2 x i16> %b to <2 x i32>
  %mul.i = mul nsw <2 x i32> %conv6.i, %conv.i
  %0 = extractelement <2 x i32> %mul.i, i64 0
  %1 = extractelement <2 x i32> %mul.i, i64 1
  %add.i = add nsw i32 %0, %1
  %cond1.i.i = tail call i32 @llvm.sadd.sat.i32(i32 %add.i, i32 %c)
  ret i32 %cond1.i.i
}

declare i32 @llvm.sadd.sat.i32(i32, i32)
declare i32 @llvm.uadd.sat.i32(i32, i32)
