// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -emit-llvm -o - %s | FileCheck %s

// Check that structs containing floats or full-sized integers (i32, i64) are
// NOT coerced to integer arrays. They should preserve their original types.
// However, structs containing only sub-32-bit integer types (char, short)
// should still be packed into i32 registers.

// === Structs with floats - should NOT be coerced to integers ===

typedef struct fp_int_pair {
    float f;
    int i;
} fp_int_pair;

// CHECK-LABEL: define{{.*}} %struct.fp_int_pair @return_fp_int_pair(float %x.coerce0, i32 %x.coerce1)
// CHECK: ret %struct.fp_int_pair
fp_int_pair return_fp_int_pair(fp_int_pair x) {
    return x;
}

typedef struct int_fp_pair {
    int i;
    float f;
} int_fp_pair;

// CHECK-LABEL: define{{.*}} %struct.int_fp_pair @return_int_fp_pair(i32 %x.coerce0, float %x.coerce1)
// CHECK: ret %struct.int_fp_pair
int_fp_pair return_int_fp_pair(int_fp_pair x) {
    return x;
}

typedef struct two_floats {
    float a;
    float b;
} two_floats;

// CHECK-LABEL: define{{.*}} %struct.two_floats @return_two_floats(float %x.coerce0, float %x.coerce1)
// CHECK: ret %struct.two_floats
two_floats return_two_floats(two_floats x) {
    return x;
}

// === Structs with full-sized integers - should NOT be coerced ===

typedef struct two_ints {
    int a;
    int b;
} two_ints;

// CHECK-LABEL: define{{.*}} %struct.two_ints @return_two_ints(i32 %x.coerce0, i32 %x.coerce1)
// CHECK: ret %struct.two_ints
two_ints return_two_ints(two_ints x) {
    return x;
}

// === Structs with only sub-32-bit integers - SHOULD be coerced ===

// Structs of small integers <= 32 bits should be coerced to i32
typedef struct small_struct {
    short a;
    short b;
} small_struct;

// CHECK-LABEL: define{{.*}} i32 @return_small_struct(i32 %x.coerce)
small_struct return_small_struct(small_struct x) {
    return x;
}

// Structs of small integers <= 16 bits should be coerced to i16
typedef struct tiny_struct {
    char a;
    char b;
} tiny_struct;

// CHECK-LABEL: define{{.*}} i16 @return_tiny_struct(i16 %x.coerce)
tiny_struct return_tiny_struct(tiny_struct x) {
    return x;
}

// Struct of 8 chars (64 bits) should be coerced to [2 x i32]
typedef struct eight_chars {
    char a, b, c, d, e, f, g, h;
} eight_chars;

// CHECK-LABEL: define{{.*}} [2 x i32] @return_eight_chars([2 x i32] %x.coerce)
eight_chars return_eight_chars(eight_chars x) {
    return x;
}

// Struct of 4 chars (32 bits) should be coerced to i32
typedef struct four_chars {
    char a, b, c, d;
} four_chars;

// CHECK-LABEL: define{{.*}} i32 @return_four_chars(i32 %x.coerce)
four_chars return_four_chars(four_chars x) {
    return x;
}

// === Mixed tests - floats prevent coercion even with small integers ===

typedef struct char_and_float {
    char c;
    float f;
} char_and_float;

// CHECK-LABEL: define{{.*}} %struct.char_and_float @return_char_and_float(i8 %x.coerce0, float %x.coerce1)
// CHECK: ret %struct.char_and_float
char_and_float return_char_and_float(char_and_float x) {
    return x;
}
